apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitwise-frontend-deployment
  labels:
    app: splitwise-frontend
  namespace: splitwise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: splitwise-frontend
  template:
    metadata:
      labels:
        app: splitwise-frontend

    spec:
      containers:
        - name: splitwise-frontend
          image: 194006481856.dkr.ecr.us-west-2.amazonaws.com/my-app:fd425aca
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # env:
          #   - name: VITE_BACKEND_URL
          #     value: "http://mern-backend-service.mern-app.svc.cluster.local:5000"