apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitwise-frontend-deployment
  labels:
    app: splitwise-frontend
  namespace: splitwise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: splitwise-frontend
  template:
    metadata:
      labels:
        app: splitwise-frontend

    spec:
      containers:
        - name: splitwise-frontend
          image: 310997740486.dkr.ecr.ap-south-1.amazonaws.com/splitwise-frontend:632e7f6f88e29a83c9731ee8d6e6293eece54706-10
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # env:
          #   - name: VITE_BACKEND_URL
          #     value: "http://mern-backend-service.mern-app.svc.cluster.local:5000"